using AetherBoy.Runtime;
using GameboyAdvanced.Core;
using GameboyAdvanced.Core.Debug;
using GameboyAdvanced.Core.Input;
using GameboyAdvanced.Core.Rom;

namespace AetherBoy.RuntimeTests;

[TestClass]
public sealed class GbaCheatProgramTests
{
    private static (Device Device, GbaCheatEngine Cheats) Create(byte[]? rom = null)
    {
        var device = new Device([], new GamePak(rom ?? new byte[512]), new TestDebugger(), true);
        var cheats = new GbaCheatEngine();
        cheats.Attach(device);
        return (device, cheats);
    }

    // Fixed fixtures generated by the ORIGINAL mGBA C cipher routines compiled
    // with gcc, not by a C# encrypt helper mirroring the production decoder.
    [TestMethod]
    [DataRow("CB:9ABCDEF0 1234 + 932C7D22 AC8D", 0x02000010u, 0xBEEFu, 2)]
    [DataRow("AR3:9C7FE77C A5352DCA + 24EBB0A7 64406898", 0x02000020u, 0x12345678u, 4)]
    [DataRow("GS:5483EE7B 2C769928 + 46BF66C5 A0AF15C2", 0x02000030u, 0xCAFEu, 2)]
    public void OriginalMgbaCipherFixturesExecuteAcrossMasterReseeding(string code, uint address, uint value, int width)
    {
        var (device, cheats) = Create();
        cheats.Add("fixture", code);
        cheats.Apply(device);
        Assert.AreEqual(value, device.ReadCheatMemory(address, width));
    }

    [TestMethod]
    public void SeparateSetInheritsMasterCipherAndFailedCompilationDoesNotChangeIt()
    {
        var (device, cheats) = Create();
        cheats.Add("master", "CB:9ABCDEF0 1234");
        Assert.ThrowsExactly<FormatException>(() => cheats.Add("bad", "AR3RAW:DEADFACE 0000FFFF + 00000000 80000000"));
        cheats.Add("body", "CB:932C7D22 AC8D");
        cheats.Apply(device);
        Assert.AreEqual(0xBEEFu, device.ReadCheatMemory(0x02000010, 2));
        Assert.HasCount(2, cheats.CaptureSnapshots());
    }

    [TestMethod]
    public void CodeBreakerSlideAndByteOrderedListWriteEveryElement()
    {
        var (device, cheats) = Create();
        cheats.Add("slide", "CB:42000000 0010 + 00020003 0004");
        cheats.Add("list", "CB:52000020 0005 + 11223344 5566 + 778899AA 0000");
        cheats.Apply(device);
        Assert.AreEqual(0x10u, device.ReadCheatMemory(0x02000000, 2));
        Assert.AreEqual(0x12u, device.ReadCheatMemory(0x02000004, 2));
        Assert.AreEqual(0x14u, device.ReadCheatMemory(0x02000008, 2));
        uint[] expected = [0x2211, 0x4433, 0x6655, 0x8877, 0xAA99];
        for (int i = 0; i < expected.Length; i++) Assert.AreEqual(expected[i], device.ReadCheatMemory(0x02000020 + (uint)i * 2, 2));
    }

    [TestMethod]
    public void ConditionSkipsTheEntireRepeatedCommand()
    {
        var (device, cheats) = Create();
        cheats.Add("conditional slide", "CB:72000000 0001 + 42000010 0055 + 00000003 0002 + 82000020 BEEF");
        cheats.Apply(device);
        Assert.AreEqual(0u, device.ReadCheatMemory(0x02000012, 2));
        Assert.AreEqual(0xBEEFu, device.ReadCheatMemory(0x02000020, 2));
        device.PokeHalfWord(0x02000000, 1);
        cheats.Apply(device);
        Assert.AreEqual(0x55u, device.ReadCheatMemory(0x02000014, 2));
    }

    [TestMethod]
    public void CodeBreakerKeyConditionUsesEmulatedButtons()
    {
        var (device, cheats) = Create();
        cheats.Add("A", "CB:D0000020 0001 + 32000010 0055");
        cheats.Apply(device);
        Assert.AreEqual(0u, device.ReadCheatMemory(0x02000010, 1));
        device.PressKey(Key.A);
        cheats.Apply(device);
        Assert.AreEqual(0x55u, device.ReadCheatMemory(0x02000010, 1));
    }

    [TestMethod]
    [DataRow(false)]
    [DataRow(true)]
    public void ActionReplayBlockElseAndEndSelectOnlyTheirBranch(bool condition)
    {
        var (device, cheats) = Create();
        device.PokeByte(0x02000000, condition ? (byte)1 : (byte)0);
        cheats.Add("branch", "AR3RAW:88200000 00000001 + 00200010 00000011 + 00200011 00000012 + 00000000 60000000 + 00200010 00000022 + 00000000 40000000 + 00200012 00000033");
        cheats.Apply(device);
        Assert.AreEqual(condition ? 0x11u : 0x22u, device.ReadCheatMemory(0x02000010, 1));
        Assert.AreEqual(condition ? 0x12u : 0u, device.ReadCheatMemory(0x02000011, 1));
        Assert.AreEqual(0x33u, device.ReadCheatMemory(0x02000012, 1));
    }

    [TestMethod]
    public void ActionReplaySignedComparisonDiffersFromUnsignedAndTwoLineSkip()
    {
        var (device, cheats) = Create();
        device.PokeByte(0x02000000, 0xFF);
        cheats.Add("signed", "AR3RAW:18200000 00000001 + 00200010 00000011");
        cheats.Add("unsigned", "AR3RAW:28200000 00000001 + 00200011 00000022");
        cheats.Add("next two", "AR3RAW:48200000 00000001 + 00200012 00000233 + 00200016 00000044 + 00200017 00000055");
        cheats.Apply(device);
        Assert.AreEqual(0x11u, device.ReadCheatMemory(0x02000010, 1));
        Assert.AreEqual(0u, device.ReadCheatMemory(0x02000011, 1));
        Assert.AreEqual(0u, device.ReadCheatMemory(0x02000014, 1));
        Assert.AreEqual(0u, device.ReadCheatMemory(0x02000016, 1));
        Assert.AreEqual(0x55u, device.ReadCheatMemory(0x02000017, 1));
    }

    [TestMethod]
    public void ActionReplayIndirectReevaluatesPointerAndIgnoresInvalidTarget()
    {
        var (device, cheats) = Create();
        cheats.Add("pointer", "AR3RAW:42200000 0001BEEF");
        device.PokeWord(0x02000000, 0xFFFFFFFF);
        cheats.Apply(device);
        device.PokeWord(0x02000000, 0x02000020);
        cheats.Apply(device);
        Assert.AreEqual(0xBEEFu, device.ReadCheatMemory(0x02000022, 2));
        device.PokeWord(0x02000000, 0x02000030);
        cheats.Apply(device);
        Assert.AreEqual(0xBEEFu, device.ReadCheatMemory(0x02000032, 2));
    }

    [TestMethod]
    public void ActionReplaySlideUsesValueAndAddressIncrements()
    {
        var (device, cheats) = Create();
        cheats.Add("slide", "AR3RAW:00000000 82200010 + 00000020 01030002");
        cheats.Apply(device);
        Assert.AreEqual(0x20u, device.ReadCheatMemory(0x02000010, 2));
        Assert.AreEqual(0x21u, device.ReadCheatMemory(0x02000014, 2));
        Assert.AreEqual(0x22u, device.ReadCheatMemory(0x02000018, 2));
    }

    [TestMethod]
    public void GameSharkAddressListConditionsAndDeviceButtonExecute()
    {
        var (device, cheats) = Create();
        cheats.Add("list", "GSRAW:30000003 02000000 + 02000004 02000008");
        cheats.Add("if", "GSRAW:D2000004 00000000 + 12000020 0000BEEF");
        cheats.Add("button", "GSRAW:82100030 00000055");
        cheats.Apply(device);
        Assert.AreEqual(0x02000000u, device.ReadCheatMemory(0x02000000, 4));
        Assert.AreEqual(0x02000000u, device.ReadCheatMemory(0x02000008, 4));
        Assert.AreEqual(0xBEEFu, device.ReadCheatMemory(0x02000020, 2));
        Assert.AreEqual(0u, device.ReadCheatMemory(0x02000030, 1));
        cheats.ButtonPressed = true;
        cheats.Apply(device);
        Assert.AreEqual(0x55u, device.ReadCheatMemory(0x02000030, 1));
    }

    [TestMethod]
    public void ActionReplayButtonAndIoWriteAreAvailable()
    {
        var (device, cheats) = Create();
        cheats.Add("button", "AR3RAW:00000000 14200030 + 12345678 00000000");
        cheats.Add("io", "AR3RAW:C6000000 00000403");
        cheats.Apply(device);
        Assert.AreEqual(0x403u, device.ReadCheatMemory(0x04000000, 2));
        Assert.AreEqual(0u, device.ReadCheatMemory(0x02000030, 4));
        cheats.ButtonPressed = true; cheats.Apply(device);
        Assert.AreEqual(0x12345678u, device.ReadCheatMemory(0x02000030, 4));
    }

    [TestMethod]
    public void OverlappingRomPatchesRestorePreviousEntryAndOriginalOnRemoval()
    {
        byte[] source = new byte[512]; source[256] = 0x7A;
        var (device, cheats) = Create(source);
        var first = cheats.Add("first", "GSRAW:60000080 00001111");
        var second = cheats.Add("second", "AR3RAW:00000000 18000080 + 00002222 00000000");
        Assert.AreEqual(0x2222u, device.ReadCheatMemory(0x08000100, 2));
        cheats.Toggle(second.Id);
        Assert.AreEqual(0x1111u, device.ReadCheatMemory(0x08000100, 2));
        cheats.Toggle(second.Id); cheats.Remove(first.Id);
        Assert.AreEqual(0x2222u, device.ReadCheatMemory(0x08000100, 2));
        cheats.Remove(second.Id);
        Assert.AreEqual(0x7Au, device.ReadCheatMemory(0x08000100, 2));
        Assert.AreEqual((byte)0x7A, source[256]);
    }

    [TestMethod]
    public void MasterHookFiresExactlyOncePerThumbInstructionAndCanBeRemoved()
    {
        byte[] rom = new byte[512];
        BitConverter.GetBytes(0xE59F0000u).CopyTo(rom, 0); // LDR r0,[pc]
        BitConverter.GetBytes(0xE12FFF10u).CopyTo(rom, 4); // BX r0
        BitConverter.GetBytes(0x08000021u).CopyTo(rom, 8);
        BitConverter.GetBytes((ushort)0xE7FE).CopyTo(rom, 0x20); // Thumb B .
        var (device, cheats) = Create(rom);
        cheats.Add("master", "AR3RAW:C4000020 00000000");
        var body = cheats.Add("body", "AR3RAW:84200000 00000001");
        int hits = 0;
        device.Cpu.InstructionStarting += (address, thumb) => { if (thumb && address == 0x08000020) hits++; };
        for (int i = 0; i < 500; i++) device.RunCycle();
        Assert.IsGreaterThan(1, hits);
        Assert.AreEqual((uint)hits, device.ReadCheatMemory(0x02000000, 4));
        cheats.Apply(device); // No duplicate frame application for a hooked set.
        Assert.AreEqual((uint)hits, device.ReadCheatMemory(0x02000000, 4));
        cheats.Remove(body.Id);
        uint old = device.ReadCheatMemory(0x02000000, 4);
        for (int i = 0; i < 50; i++) device.RunCycle();
        Assert.AreEqual(old, device.ReadCheatMemory(0x02000000, 4));
    }

    [TestMethod]
    public void CheatsDoNotChangeCpuWaitStateBudget()
    {
        var (device, cheats) = Create();
        cheats.Add("condition", "CB:72000000 0000 + E2000002 0001");
        int before = device.Bus.WaitStates;
        cheats.Apply(device);
        Assert.AreEqual(before, device.Bus.WaitStates);
    }

    [TestMethod]
    [DataRow("CB:42000000 0001")]
    [DataRow("CB:52000000 0004 + 12345678 9ABC")]
    [DataRow("AR3RAW:00000000 18000000")]
    [DataRow("AR3RAW:00000000 60000000")]
    [DataRow("AR3RAW:00000000 40000000")]
    [DataRow("AR3RAW:00200000 01000055")]
    [DataRow("AR3RAW:0023FFFF 00000155")]
    [DataRow("GSRAW:30000003 00000055 + 02000000 FFFFFFFF")]
    public void BrokenProgramsCannotPublishPartialEntries(string code)
    {
        var (_, cheats) = Create();
        Assert.ThrowsExactly<FormatException>(() => cheats.Add("broken", code));
        Assert.HasCount(0, cheats.CaptureSnapshots());
    }

    [TestMethod]
    public void FormatSelectionPrefixesTheWholeSetAndPreservesExplicitCodes()
    {
        Assert.AreEqual("AR3:AAAA0000 BBBB0000\nCCCC0000 DDDD0000", CheatCodeInput.Prepare("AAAA0000 BBBB0000\nCCCC0000 DDDD0000", CheatCodeFormat.ActionReplayV3));
        Assert.AreEqual("CB:82000000 0001", CheatCodeInput.Prepare("CB:82000000 0001", CheatCodeFormat.ActionReplayV3));
        Assert.AreEqual("02000000:11", CheatCodeInput.Prepare("02000000:11", CheatCodeFormat.ActionReplayV3));
    }
}
