namespace AetherBoy.Desktop;

internal enum LinuxSettingsDestination
{
    Picture, Scaling, Fullscreen, Palette, Performance, Keyboard, Controller, ControllerStick, Shortcuts,
    Volume, Channels, Appearance, TextSize, Desktop, Profiles, Firmware, Storage,
    Saves, Backups, Gallery, Library, PatchLab, Tools, Online, Diagnostics, VideoCapture, Discord, Updates, Intro, BarcodeBoy, Language
}

internal sealed record LinuxSettingEntry(LinuxSettingsDestination Destination, string Title,
    string Description, string Location, string Keywords);

// The same destinations power the overview and search. Search never changes a preference.
internal static class LinuxSettingsCatalog
{
    internal static LinuxSettingEntry[] Entries =>
    [
        new(LinuxSettingsDestination.Language, global::AetherBoy.Runtime.Localization.UiText.Get("Display language"), "Deutsch / English", global::AetherBoy.Runtime.Localization.UiText.Get("App & files"), "language sprache deutsch english englisch system österreich schweiz"),
        new(LinuxSettingsDestination.BarcodeBoy, "Barcode Boy", global::AetherBoy.Runtime.Localization.UiText.Get("Connect the scanner and enter a card code or load a text file."), global::AetherBoy.Runtime.Localization.UiText.Get("Tools > Barcode Boy"), "barcode boy scanner namcot battle space berserker valkyrie accessory kartencode"),
        new(LinuxSettingsDestination.Intro, global::AetherBoy.Runtime.Localization.UiText.Get("Game start animation"), global::AetherBoy.Runtime.Localization.UiText.Get("Choose your logo and sound or disable the intro."), global::AetherBoy.Runtime.Localization.UiText.Get("App & files > Firmware > Start animation"), "boot intro startup logo sound ton bild png wav startanimation"),
        new(LinuxSettingsDestination.Discord, global::AetherBoy.Runtime.Localization.UiText.Get("Discord activity"), global::AetherBoy.Runtime.Localization.UiText.Get("Choose whether to share activity and game titles."), global::AetherBoy.Runtime.Localization.UiText.Get("App & files > Desktop > Discord"), "rich presence privacy spielstatus datenschutz application id"),
        new(LinuxSettingsDestination.Updates, "Updates", global::AetherBoy.Runtime.Localization.UiText.Get("Check for release packages and download them."), global::AetherBoy.Runtime.Localization.UiText.Get("App & files > Files & updates"), "version update upgrade download aktualisierung"),
        new(LinuxSettingsDestination.VideoCapture, global::AetherBoy.Runtime.Localization.UiText.Get("Record gameplay video"), global::AetherBoy.Runtime.Localization.UiText.Get("Record the native picture and game audio as AVI."), global::AetherBoy.Runtime.Localization.UiText.Get("Tools > Record video"), "recording gameplay capture avi film aufnahme"),
        new(LinuxSettingsDestination.Picture, global::AetherBoy.Runtime.Localization.UiText.Get("Picture filter"), global::AetherBoy.Runtime.Localization.UiText.Get("Choose sharp pixels, smoothing or an LCD grid."), global::AetherBoy.Runtime.Localization.UiText.Get("Graphics > Picture"), "video graphics grafik bild filter display shader"),
        new(LinuxSettingsDestination.Scaling, global::AetherBoy.Runtime.Localization.UiText.Get("Picture size"), global::AetherBoy.Runtime.Localization.UiText.Get("Use whole pixels or fit the game to the available space."), global::AetherBoy.Runtime.Localization.UiText.Get("Graphics > Picture"), "scale scaling integer aspect ratio zoom pixel auflösung skalierung bildgröße"),
        new(LinuxSettingsDestination.Fullscreen, global::AetherBoy.Runtime.Localization.UiText.Get("Fullscreen"), global::AetherBoy.Runtime.Localization.UiText.Get("Switch between a window and fullscreen with F11."), global::AetherBoy.Runtime.Localization.UiText.Get("Graphics > Picture"), "window display monitor vollbild fenster"),
        new(LinuxSettingsDestination.Palette, global::AetherBoy.Runtime.Localization.UiText.Get("Game Boy colors"), global::AetherBoy.Runtime.Localization.UiText.Get("Change the four colors used by original Game Boy games."), global::AetherBoy.Runtime.Localization.UiText.Get("Graphics > Game Boy colors"), "dmg palette color colour farbe farben"),
        new(LinuxSettingsDestination.Performance, global::AetherBoy.Runtime.Localization.UiText.Get("Frame display and performance"), global::AetherBoy.Runtime.Localization.UiText.Get("Reduce displayed frames or show the FPS overlay."), global::AetherBoy.Runtime.Localization.UiText.Get("Graphics > Performance"), "frameskip speed fps slow latency leistung langsam"),
        new(LinuxSettingsDestination.Controller, global::AetherBoy.Runtime.Localization.UiText.Get("Controller buttons"), global::AetherBoy.Runtime.Localization.UiText.Get("Select a controller and remap its buttons."), global::AetherBoy.Runtime.Localization.UiText.Get("Controls > Controller"), "gamepad joystick input bind mapping xbox playstation tasten tastenbelegung belegung"),
        new(LinuxSettingsDestination.ControllerStick, global::AetherBoy.Runtime.Localization.UiText.Get("Controller stick deadzone"), global::AetherBoy.Runtime.Localization.UiText.Get("Adjust stick sensitivity and test movement live."), global::AetherBoy.Runtime.Localization.UiText.Get("Controls > Controller > Stick settings"), "analog joystick drift sensitivity stick deadzone totzone empfindlichkeit"),
        new(LinuxSettingsDestination.Keyboard, global::AetherBoy.Runtime.Localization.UiText.Get("Keyboard keys"), global::AetherBoy.Runtime.Localization.UiText.Get("Change the keys used to play and restore the defaults."), global::AetherBoy.Runtime.Localization.UiText.Get("Controls > Keyboard"), "input bind mapping tastatur tastenbelegung turbo pause"),
        new(LinuxSettingsDestination.Shortcuts, global::AetherBoy.Runtime.Localization.UiText.Get("App shortcuts"), global::AetherBoy.Runtime.Localization.UiText.Get("Find the keys for save states, screenshots and settings."), global::AetherBoy.Runtime.Localization.UiText.Get("Controls > App shortcuts"), "hotkey shortcut keys kürzel tastenkürzel f5 f7 f8 f9 f10 f11 f12"),
        new(LinuxSettingsDestination.Volume, global::AetherBoy.Runtime.Localization.UiText.Get("Volume and mute"), global::AetherBoy.Runtime.Localization.UiText.Get("Set the sound level or mute game audio."), "Audio", "sound audio volume mute lautstärke ton stumm"),
        new(LinuxSettingsDestination.Channels, global::AetherBoy.Runtime.Localization.UiText.Get("Sound channels"), global::AetherBoy.Runtime.Localization.UiText.Get("Turn individual Game Boy sound channels on or off."), "Audio", "audio channel sound kanal kanäle"),
        new(LinuxSettingsDestination.Appearance, global::AetherBoy.Runtime.Localization.UiText.Get("App colors"), global::AetherBoy.Runtime.Localization.UiText.Get("Choose the accent and background colors of AetherBoy."), global::AetherBoy.Runtime.Localization.UiText.Get("App & files > Appearance"), "theme appearance hintergrund aussehen design farbe farben"),
        new(LinuxSettingsDestination.TextSize, global::AetherBoy.Runtime.Localization.UiText.Get("Text size"), global::AetherBoy.Runtime.Localization.UiText.Get("Make interface labels easier to read."), global::AetherBoy.Runtime.Localization.UiText.Get("App & files > Desktop"), "font accessibility schrift schriftgröße lesbarkeit"),
        new(LinuxSettingsDestination.Desktop, global::AetherBoy.Runtime.Localization.UiText.Get("Pause when unfocused"), global::AetherBoy.Runtime.Localization.UiText.Get("Pause the game when you switch to another window."), global::AetherBoy.Runtime.Localization.UiText.Get("App & files > Desktop"), "focus background automatic pause hintergrund fokus"),
        new(LinuxSettingsDestination.Profiles, global::AetherBoy.Runtime.Localization.UiText.Get("Settings for this game"), global::AetherBoy.Runtime.Localization.UiText.Get("Give a game its own graphics, audio and keyboard settings."), global::AetherBoy.Runtime.Localization.UiText.Get("App & files > Game profiles"), "global profile defaults spielprofil profil standard"),
        new(LinuxSettingsDestination.Firmware, global::AetherBoy.Runtime.Localization.UiText.Get("Boot ROM and BIOS"), global::AetherBoy.Runtime.Localization.UiText.Get("Import firmware and choose whether to use it when opening a game."), global::AetherBoy.Runtime.Localization.UiText.Get("App & files > Firmware"), "bios firmware boot startup start"),
        new(LinuxSettingsDestination.Storage, global::AetherBoy.Runtime.Localization.UiText.Get("Data folder"), global::AetherBoy.Runtime.Localization.UiText.Get("Find saved games, screenshots and recordings on this computer."), global::AetherBoy.Runtime.Localization.UiText.Get("App & files > Files"), "file path folder storage ordner dateien speicherort"),
        new(LinuxSettingsDestination.Saves, global::AetherBoy.Runtime.Localization.UiText.Get("Save states and resume"), global::AetherBoy.Runtime.Localization.UiText.Get("Save a point in the game or continue from an earlier one."), global::AetherBoy.Runtime.Localization.UiText.Get("Save states"), "save load resume rewind spielstand speichern laden zurückspulen"),
        new(LinuxSettingsDestination.Backups, global::AetherBoy.Runtime.Localization.UiText.Get("Save backups"), global::AetherBoy.Runtime.Localization.UiText.Get("Import, export or restore a battery save."), global::AetherBoy.Runtime.Localization.UiText.Get("Save states > Backups"), "backup recovery save import export sicherung spielstand"),
        new(LinuxSettingsDestination.Gallery, global::AetherBoy.Runtime.Localization.UiText.Get("Save previews"), global::AetherBoy.Runtime.Localization.UiText.Get("Inspect the images and timestamps of saved states."), global::AetherBoy.Runtime.Localization.UiText.Get("Save states > Gallery"), "gallery preview slot vorschau"),
        new(LinuxSettingsDestination.Library, global::AetherBoy.Runtime.Localization.UiText.Get("Game library"), global::AetherBoy.Runtime.Localization.UiText.Get("Find recent games, favorites and cartridge titles."), global::AetherBoy.Runtime.Localization.UiText.Get("Library"), "rom game open recent favorite bibliothek spiel öffnen"),
        new(LinuxSettingsDestination.PatchLab, global::AetherBoy.Runtime.Localization.UiText.Get("ROM patches"), global::AetherBoy.Runtime.Localization.UiText.Get("Apply a patch to a copy of a ROM."), global::AetherBoy.Runtime.Localization.UiText.Get("Library > Patch Lab"), "patch ips bps ups rom hack"),
        new(LinuxSettingsDestination.Tools, global::AetherBoy.Runtime.Localization.UiText.Get("Screenshots, recordings and cheats"), global::AetherBoy.Runtime.Localization.UiText.Get("Capture a game image, record WAV audio or manage cheats."), global::AetherBoy.Runtime.Localization.UiText.Get("Tools"), "screenshot wav recording capture cheat aufnahme bildschirmfoto"),
        new(LinuxSettingsDestination.Online, "Online Link", global::AetherBoy.Runtime.Localization.UiText.Get("Open the experimental connection tools and room setup."), global::AetherBoy.Runtime.Localization.UiText.Get("Tools > Online Link"), "online link room multiplayer raum verbindung"),
        new(LinuxSettingsDestination.Diagnostics, global::AetherBoy.Runtime.Localization.UiText.Get("Diagnostics and reports"), global::AetherBoy.Runtime.Localization.UiText.Get("Inspect the session and export a local technical report."), global::AetherBoy.Runtime.Localization.UiText.Get("Diagnostics"), "error debug log report fehler bericht diagnose")
    ];

    internal static LinuxSettingEntry[] Search(string query)
    {
        string[] words = query.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        return Entries.Where(entry => words.All(word =>
                $"{entry.Title} {entry.Description} {entry.Location} {entry.Keywords}".Contains(word, StringComparison.OrdinalIgnoreCase)))
            .OrderByDescending(entry => words.Count(word => entry.Title.Contains(word, StringComparison.OrdinalIgnoreCase)))
            .ToArray();
    }
}
