//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nanoboy.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Channel1Enable {
            get {
                return ((bool)(this["Channel1Enable"]));
            }
            set {
                this["Channel1Enable"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Channel2Enable {
            get {
                return ((bool)(this["Channel2Enable"]));
            }
            set {
                this["Channel2Enable"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Channel3Enable {
            get {
                return ((bool)(this["Channel3Enable"]));
            }
            set {
                this["Channel3Enable"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Channel4Enable {
            get {
                return ((bool)(this["Channel4Enable"]));
            }
            set {
                this["Channel4Enable"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AudioEnable {
            get {
                return ((bool)(this["AudioEnable"]));
            }
            set {
                this["AudioEnable"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int VideoScaleFactor {
            get {
                return ((int)(this["VideoScaleFactor"]));
            }
            set {
                this["VideoScaleFactor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Frameskip {
            get {
                return ((int)(this["Frameskip"]));
            }
            set {
                this["Frameskip"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y")]
        public global::System.Windows.Forms.Keys KeyA {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyA"]));
            }
            set {
                this["KeyA"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X")]
        public global::System.Windows.Forms.Keys KeyB {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyB"]));
            }
            set {
                this["KeyB"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public global::System.Windows.Forms.Keys KeyStart {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyStart"]));
            }
            set {
                this["KeyStart"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("V")]
        public global::System.Windows.Forms.Keys KeySelect {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeySelect"]));
            }
            set {
                this["KeySelect"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Up")]
        public global::System.Windows.Forms.Keys KeyUp {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyUp"]));
            }
            set {
                this["KeyUp"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Down")]
        public global::System.Windows.Forms.Keys KeyDown {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyDown"]));
            }
            set {
                this["KeyDown"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public global::System.Windows.Forms.Keys KeyLeft {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyLeft"]));
            }
            set {
                this["KeyLeft"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right")]
        public global::System.Windows.Forms.Keys KeyRight {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyRight"]));
            }
            set {
                this["KeyRight"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int SampleRate {
            get {
                return ((int)(this["SampleRate"]));
            }
            set {
                this["SampleRate"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q")]
        public global::System.Windows.Forms.Keys KeyL {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyL"]));
            }
            set {
                this["KeyL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E")]
        public global::System.Windows.Forms.Keys KeyR {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyR"]));
            }
            set {
                this["KeyR"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public int GamepadAButton {
            get {
                return ((int)(this["GamepadAButton"]));
            }
            set {
                this["GamepadAButton"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6144")]
        public int GamepadBButton {
            get {
                return ((int)(this["GamepadBButton"]));
            }
            set {
                this["GamepadBButton"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int GamepadStartButton {
            get {
                return ((int)(this["GamepadStartButton"]));
            }
            set {
                this["GamepadStartButton"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int GamepadSelectButton {
            get {
                return ((int)(this["GamepadSelectButton"]));
            }
            set {
                this["GamepadSelectButton"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("256")]
        public int GamepadLButton {
            get {
                return ((int)(this["GamepadLButton"]));
            }
            set {
                this["GamepadLButton"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public int GamepadRButton {
            get {
                return ((int)(this["GamepadRButton"]));
            }
            set {
                this["GamepadRButton"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("256")]
        public int GamepadQuickLoadButton {
            get {
                return ((int)(this["GamepadQuickLoadButton"]));
            }
            set {
                this["GamepadQuickLoadButton"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public int GamepadQuickSaveButton {
            get {
                return ((int)(this["GamepadQuickSaveButton"]));
            }
            set {
                this["GamepadQuickSaveButton"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PaletteIndex {
            get {
                return ((int)(this["PaletteIndex"]));
            }
            set {
                this["PaletteIndex"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DisplayFilterIndex {
            get {
                return ((int)(this["DisplayFilterIndex"]));
            }
            set {
                this["DisplayFilterIndex"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SaveSlot {
            get {
                return ((int)(this["SaveSlot"]));
            }
            set {
                this["SaveSlot"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BootRomEnable {
            get {
                return ((bool)(this["BootRomEnable"]));
            }
            set {
                this["BootRomEnable"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int AudioVolume {
            get {
                return ((int)(this["AudioVolume"]));
            }
            set {
                this["AudioVolume"] = value;
            }
        }
    }
}
